repos:
  - repo: https://github.com/tsvikas/sync-with-uv
    rev: v0.4.0  # replace with the latest version
    hooks:
      - id: sync-with-uv
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.4
    hooks:
      - id: ruff-format
        types_or: [ python, pyi ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        types_or: [ python, pyi ]
      - id: end-of-file-fixer
        types_or: [ python, pyi ]
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
